### ISSUE TITLE
Connect to LMEC Storyblok API

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/teaching-portal#2]
LMEC's Storyblok account is with the user `info@leventhalmap.org` and I will provide the PW separately.

All content for this project will be in the `teaching-portal` directory. (I've also created a `main-site` directory which is a future place to put contact for the LMEC homepage if we end up porting it to Storyblok.)

So far there is a single type of Blok, `lesson-plan`, which will be the initial content type for testing out this CMS integration.

**Comment by alexandergknoll** [comment]
Will get a simple integration going for the purposes of this task, but some other things we'll need to implement (either as part of this issue or we could split into new issues):

- Add a Markdown processor (and integrate with [Tailwind Typography](https://tailwindcss.com/docs/typography-plugin) for sensible default styles)
- Create corresponding Body/Block components in Astro

**Comment by garrettdashnelson** [comment]
I'm only just learning/experimenting with this, but I believe there's a `renderRichText` function included in `@storyblok/astro` which may obviate the need for a Markdown processor - [see docs here](https://docs.astro.build/en/guides/cms/storyblok/)

**Comment by alexandergknoll** [comment]
I realized that the `renderRichText` function is for the Rich Text field type rather than Markdown - it looks like Astro recommends using [marked](https://github.com/markedjs/marked) for processing remote markdown, so I went with that:

https://docs.astro.build/en/guides/markdown-content/#fetching-remote-markdown

I also added (DOMPurify)[https://github.com/cure53/DOMPurify] to sanitize HTML and protect against XSS attacks.  I am not entirely clear on whether this is required with Astro, but it seems like a good precaution; and since we plan to compile the site statically I don't think this is a performance concern - but of course would love to hear any feedback if you feel otherwise!
