### ISSUE TITLE
Create `src/pages/lesson-plans/[lesson-plan].astro` to dynamically generate lesson plan content pages

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/teaching-portal#5]
The file route schema referenced in the title is just a suggestion.

This page should load all of the `lesson-plan` content pages available in Storyblok and generate a single page for each one.

@garrettdashnelson will provide some simple layout ideas as a sketch.

**Comment by garrettdashnelson** [comment]
![lesson plan page](https://github.com/bplmaps/teaching-portal/assets/2424901/81173af7-94f2-40fd-9fcc-17d809fff295)

**Comment by alexandergknoll** [comment]
@garrettdashnelson just throwing an idea out here for the future - but what are your thoughts on having a sidebar to the left that contains things like the Lesson Objectives, Essential Questions, etc. with the body of the lesson being in the main content area on the right?  The objectives, questions, etc. would stay fixed with you as you scrolled down throughout the lesson.  I was looking at this example from Tailwind UI that seemed pretty cool: https://protocol.tailwindui.com/

At this stage most likely it's premature to do that until we have some time to iterate on the schema in Storyblok, etc. so I'll go with what you've outlined but I thought I would just mention here.  Looks good!

**Comment by garrettdashnelson** [comment]
@alexandergknoll Definitely! I was actually thinking in a future iteration that we could additional populate a sidebar like that using the header tags of the body block as well. 

Also, they absolutely got me with the text at https://api.protocol.chat ....

**Comment by alexandergknoll** [comment]
Added a basic template for this; I did not implement an IIIF viewer yet, but if that's meant to be part of milestone 1 please let me know!

**Comment by alexandergknoll** [comment]
@garrettdashnelson I think we can close this one now that we have the IIIF component added but let me know if I missed anything!
